# Download image .net core sdk for develop and build (Ubuntu 20.04)
FROM mcr.microsoft.com/dotnet/sdk:5.0-focal

USER root
# Update and install necessary package
RUN apt-get update -y && \
    apt-get install build-essential -y && \
# Install node 14, npm, angular
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt install nodejs -y && \
    npm install -g @angular/cli@13.2.5 && \
    npm install -g npm
