# Download image to run SQLServer 2019 and sql-tools
FROM mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
# Download image .net core runtime for run
FROM mcr.microsoft.com/dotnet/runtime:5.0

USER root
# Update and install necessary package
RUN apt-get update && apt-get update -y && \
    apt-get install -y curl && \
    apt-get install -y gnupg && \
    apt-get install -y wget && \
    apt-get install build-essential -y

# Install feature full text search for sql server 2019
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list | tee /etc/apt/sources.list.d/mssql-server.list
RUN apt-get update
RUN apt-get install -y mssql-server-fts

# Install ssh from source for running sql-server
COPY ./config /config
WORKDIR /config/libc6_2.31/

RUN dpkg -i libcrypt1_4.4.18-4_amd64.deb
RUN dpkg -i gcc-10-base_10.2.1-6_amd64.deb
RUN dpkg -i libgcc-s1_10.2.1-6_amd64.deb
RUN dpkg -i libc6_2.31-13+deb11u2_amd64.deb
RUN dpkg -i libc-bin_2.31-13+deb11u2_amd64.deb

RUN dpkg --configure -a
RUN apt-get -f install -y
RUN apt-get update -y

WORKDIR /

# Config nginx
RUN mkdir -p /app/html
RUN mv /config/nginx/html/* /app/html

# Clean package
RUN apt-get remove curl -y && \
    apt-get remove gnupg -y && \
    apt-get autoclean -y

# nginx, mssql-server, ssh
EXPOSE 80

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Thesis1234
# Run Service
CMD /usr/bin/nginx -c /config/nginx/nginx.conf && /opt/mssql/bin/sqlservr
