name: Docker environment for develop

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
    - name: Docker env for develop
      run: |
        docker build -t app-env:v01 . -f Dockerfile-develop
    - name: Docker env for release
      run: |
        docker build -t app-env:v01 . -f Dockerfile-release
        