name: Docker environment for develop

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker env for develop
      run: |
        docker build -t app-env:v3 . -f Dockerfile-env
    - name: Docker push
      run: |
        docker push eraa/app-env:v3

        