name: Docker environment for develop

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker env for develop
      run: |
        docker build -t build-app:v3 . -f dockerfile-build
    - name: Docker push
      run: |
        docker push eraa/build-app:v3
